"""Repository and transaction ports implemented by infrastructure adapters."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date, datetime, timedelta
from types import TracebackType
from typing import Protocol, Self

from swim_coach.domain.actions import (
    ActionApproval,
    ActionExecution,
    ActionProposal,
    ExternalWorkoutBinding,
)
from swim_coach.domain.activities import (
    ActivityAnalysis,
    FileArtifact,
    NormalizedActivity,
    SessionFeedback,
    WorkoutExecutionMatch,
)
from swim_coach.domain.athlete import (
    AthleteConstraint,
    AthleteProfile,
    AvailabilityRule,
    Device,
    Pool,
)
from swim_coach.domain.garmin import (
    Activity,
    ActivityImport,
    ActivityImportStatus,
    GarminConnection,
    RawProviderPayload,
    SyncCursor,
    SyncRun,
)
from swim_coach.domain.goals import GoalMilestone, TrainingGoal
from swim_coach.domain.identity import (
    AppUser,
    AuthIdentity,
    OidcLoginAttempt,
    WebSession,
)
from swim_coach.domain.operations import (
    ApiIdempotencyRecord,
    AuditEvent,
    Job,
    McpToolInvocation,
    Notification,
    OutboxEvent,
)
from swim_coach.domain.planning import PlanningRun, TrainingDecisionRecord, TrainingRuleSet
from swim_coach.domain.shared.types import JsonObject
from swim_coach.domain.shared.value_objects import EntityId, UserId
from swim_coach.domain.workouts import (
    PlannedWorkout,
    WorkoutRevision,
    WorkoutSchedule,
    WorkoutTemplate,
)


class UsersRepository(Protocol):
    async def get(self, user_id: UserId) -> AppUser | None: ...
    async def get_by_email(self, email: str) -> AppUser | None: ...
    async def add(self, user: AppUser) -> None: ...
    async def update(self, user: AppUser, *, expected_version: int) -> None: ...
    async def list_active(self) -> Sequence[AppUser]: ...


class IdentitiesRepository(Protocol):
    async def get(self, provider: str, subject: str) -> AuthIdentity | None: ...
    async def add(self, identity: AuthIdentity) -> None: ...


class ProfilesRepository(Protocol):
    async def get(self, user_id: UserId) -> AthleteProfile | None: ...
    async def add(self, profile: AthleteProfile) -> None: ...
    async def update(self, profile: AthleteProfile, *, expected_version: int) -> None: ...


class PoolsRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[Pool]: ...
    async def get(self, user_id: UserId, pool_id: EntityId) -> Pool | None: ...
    async def add(self, pool: Pool) -> None: ...
    async def update(self, pool: Pool, *, expected_version: int) -> None: ...
    async def clear_default(self, user_id: UserId, *, except_id: EntityId) -> None: ...


class AvailabilityRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[AvailabilityRule]: ...
    async def replace(self, user_id: UserId, rules: Sequence[AvailabilityRule]) -> None: ...


class ConstraintsRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[AthleteConstraint]: ...
    async def add(self, constraint: AthleteConstraint) -> None: ...


class DevicesRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[Device]: ...
    async def add(self, device: Device) -> None: ...
    async def upsert(self, device: Device) -> None: ...


class GarminConnectionsRepository(Protocol):
    async def get(self, user_id: UserId) -> GarminConnection | None: ...
    async def upsert(self, connection: GarminConnection) -> None: ...
    async def update(self, connection: GarminConnection, *, expected_version: int) -> None: ...


class SyncCursorsRepository(Protocol):
    async def get(self, user_id: UserId, provider: str, entity_type: str) -> SyncCursor | None: ...
    async def upsert(self, cursor: SyncCursor) -> None: ...


class SyncRunsRepository(Protocol):
    async def add(self, run: SyncRun) -> None: ...
    async def update(self, run: SyncRun, *, expected_version: int) -> None: ...
    async def list_recent(self, user_id: UserId, *, limit: int = 20) -> Sequence[SyncRun]: ...


class RawProviderPayloadsRepository(Protocol):
    async def add_if_absent(self, payload: RawProviderPayload) -> EntityId: ...


class ActivitiesRepository(Protocol):
    async def get(self, user_id: UserId, activity_id: EntityId) -> Activity | None: ...
    async def get_by_external_id(
        self, user_id: UserId, provider: str, external_activity_id: str
    ) -> Activity | None: ...
    async def upsert(self, activity: Activity) -> tuple[ActivityImportStatus, EntityId]: ...
    async def list_recent(
        self, user_id: UserId, *, limit: int = 50, before: datetime | None = None
    ) -> Sequence[Activity]: ...


class ActivityDataRepository(Protocol):
    async def get_artifact_by_checksum(
        self, user_id: UserId, activity_id: EntityId, checksum: str, artifact_type: str
    ) -> FileArtifact | None: ...
    async def add_artifact(self, artifact: FileArtifact) -> None: ...
    async def get_normalization(
        self, user_id: UserId, normalization_id: EntityId
    ) -> NormalizedActivity | None: ...
    async def get_current_normalization(
        self, user_id: UserId, activity_id: EntityId
    ) -> NormalizedActivity | None: ...
    async def get_normalization_by_input(
        self,
        user_id: UserId,
        activity_id: EntityId,
        parser_version: str,
        input_checksum: str,
    ) -> NormalizedActivity | None: ...
    async def save_normalization(self, normalized: NormalizedActivity) -> bool: ...
    async def promote_normalization(
        self, user_id: UserId, activity_id: EntityId, normalization_id: EntityId
    ) -> None: ...
    async def get_analysis(
        self, user_id: UserId, activity_id: EntityId
    ) -> ActivityAnalysis | None: ...
    async def list_analyses(
        self, user_id: UserId, activity_ids: Sequence[EntityId]
    ) -> Sequence[ActivityAnalysis]: ...
    async def add_analysis(self, analysis: ActivityAnalysis) -> None: ...
    async def get_match(
        self, user_id: UserId, activity_id: EntityId
    ) -> WorkoutExecutionMatch | None: ...
    async def get_match_by_workout(
        self, user_id: UserId, workout_id: EntityId
    ) -> WorkoutExecutionMatch | None: ...
    async def upsert_match(self, match: WorkoutExecutionMatch) -> None: ...
    async def get_feedback(
        self, user_id: UserId, activity_id: EntityId
    ) -> SessionFeedback | None: ...
    async def list_feedbacks(
        self, user_id: UserId, activity_ids: Sequence[EntityId]
    ) -> Sequence[SessionFeedback]: ...
    async def upsert_feedback(
        self, feedback: SessionFeedback, *, expected_version: int | None
    ) -> None: ...


class ActivityImportsRepository(Protocol):
    async def add(self, activity_import: ActivityImport) -> None: ...


class GoalsRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[TrainingGoal]: ...
    async def get(self, user_id: UserId, goal_id: EntityId) -> TrainingGoal | None: ...
    async def add(self, goal: TrainingGoal) -> None: ...
    async def update(self, goal: TrainingGoal, *, expected_version: int) -> None: ...


class GoalMilestonesRepository(Protocol):
    async def list(self, user_id: UserId, goal_id: EntityId) -> Sequence[GoalMilestone]: ...
    async def add(self, milestone: GoalMilestone) -> None: ...


class WorkoutsRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[PlannedWorkout]: ...
    async def get(self, user_id: UserId, workout_id: EntityId) -> PlannedWorkout | None: ...
    async def add(self, workout: PlannedWorkout) -> None: ...
    async def update(self, workout: PlannedWorkout, *, expected_version: int) -> None: ...


class WorkoutRevisionsRepository(Protocol):
    async def list(self, user_id: UserId, workout_id: EntityId) -> Sequence[WorkoutRevision]: ...
    async def get(self, user_id: UserId, revision_id: EntityId) -> WorkoutRevision | None: ...
    async def list_many(
        self, user_id: UserId, workout_ids: Sequence[EntityId]
    ) -> Sequence[WorkoutRevision]: ...
    async def add(self, revision: WorkoutRevision) -> None: ...


class WorkoutSchedulesRepository(Protocol):
    async def get(self, user_id: UserId, workout_id: EntityId) -> WorkoutSchedule | None: ...
    async def list(
        self, user_id: UserId, workout_ids: Sequence[EntityId]
    ) -> Sequence[WorkoutSchedule]: ...
    async def upsert(self, schedule: WorkoutSchedule) -> None: ...


class WorkoutTemplatesRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[WorkoutTemplate]: ...
    async def add(self, template: WorkoutTemplate) -> None: ...


class ActionProposalsRepository(Protocol):
    async def get(self, user_id: UserId, proposal_id: EntityId) -> ActionProposal | None: ...
    async def get_for_update(
        self, user_id: UserId, proposal_id: EntityId
    ) -> ActionProposal | None: ...
    async def get_by_hash(self, user_id: UserId, action_hash: str) -> ActionProposal | None: ...
    async def list_recent(
        self, user_id: UserId, *, limit: int = 50
    ) -> Sequence[ActionProposal]: ...
    async def add(self, proposal: ActionProposal) -> None: ...
    async def update(self, proposal: ActionProposal, *, expected_version: int) -> None: ...


class ActionApprovalsRepository(Protocol):
    async def add(self, approval: ActionApproval) -> None: ...


class ActionExecutionsRepository(Protocol):
    async def get_by_proposal(
        self, user_id: UserId, proposal_id: EntityId
    ) -> ActionExecution | None: ...
    async def add(self, execution: ActionExecution) -> None: ...
    async def update(self, execution: ActionExecution, *, expected_version: int) -> None: ...


class TrainingRuleSetsRepository(Protocol):
    async def get_active(self, effective_on: date) -> TrainingRuleSet | None: ...
    async def get_by_hash(self, content_hash: str) -> TrainingRuleSet | None: ...
    async def add(self, rule_set: TrainingRuleSet) -> None: ...


class PlanningRunsRepository(Protocol):
    async def get_by_input(
        self, user_id: UserId, rule_set_id: EntityId, input_hash: str
    ) -> PlanningRun | None: ...
    async def add(self, run: PlanningRun) -> None: ...


class TrainingDecisionsRepository(Protocol):
    async def add(self, decision: TrainingDecisionRecord) -> None: ...
    async def list_for_run(
        self, user_id: UserId, planning_run_id: EntityId
    ) -> Sequence[TrainingDecisionRecord]: ...


class ExternalWorkoutBindingsRepository(Protocol):
    async def get(self, user_id: UserId, binding_id: EntityId) -> ExternalWorkoutBinding | None: ...
    async def get_by_revision_hash(
        self,
        user_id: UserId,
        provider: str,
        revision_id: EntityId,
        compiled_hash: str,
    ) -> ExternalWorkoutBinding | None: ...
    async def add(self, binding: ExternalWorkoutBinding) -> None: ...
    async def update(self, binding: ExternalWorkoutBinding, *, expected_version: int) -> None: ...


class JobsRepository(Protocol):
    async def add(self, job: Job) -> None: ...
    async def get(self, user_id: UserId, job_id: EntityId) -> Job | None: ...
    async def add_idempotent(self, job: Job) -> Job: ...
    async def get_by_idempotency_key(self, idempotency_key: str) -> Job | None: ...
    async def retry_failed(self, user_id: UserId, job_id: EntityId, at: datetime) -> Job | None: ...
    async def lease_next(
        self, worker_id: str, *, ttl: timedelta, job_types: frozenset[str]
    ) -> Job | None: ...
    async def mark_succeeded(self, job_id: EntityId, worker_id: str, at: datetime) -> bool: ...
    async def mark_failed(
        self,
        job_id: EntityId,
        worker_id: str,
        at: datetime,
        *,
        error: JsonObject,
        retry_at: datetime | None,
    ) -> bool: ...
    async def mark_needs_reconciliation(
        self, job_id: EntityId, worker_id: str, at: datetime, *, error: JsonObject
    ) -> bool: ...
    async def list_recent(self, user_id: UserId, *, limit: int = 50) -> Sequence[Job]: ...
    async def metrics(self, user_id: UserId, now: datetime) -> JsonObject: ...
    async def purge_finished(self, before: datetime) -> int: ...


class NotificationsRepository(Protocol):
    async def add_idempotent(self, notification: Notification) -> Notification: ...
    async def list_recent(self, user_id: UserId, *, limit: int = 50) -> Sequence[Notification]: ...
    async def mark_read(
        self, user_id: UserId, notification_id: EntityId, at: datetime
    ) -> Notification | None: ...


class OutboxRepository(Protocol):
    async def add(self, event: OutboxEvent) -> None: ...


class AuditRepository(Protocol):
    async def add(self, event: AuditEvent) -> None: ...


class McpToolInvocationsRepository(Protocol):
    async def add(self, invocation: McpToolInvocation) -> None: ...


class IdempotencyRepository(Protocol):
    async def get(self, scope: str, key: str, now: datetime) -> ApiIdempotencyRecord | None: ...
    async def add(self, record: ApiIdempotencyRecord) -> None: ...


class SessionsRepository(Protocol):
    async def add(self, session: WebSession) -> None: ...
    async def get_active_by_token_hash(
        self, token_hash: str, now: datetime
    ) -> WebSession | None: ...
    async def revoke(self, session_id: EntityId, at: datetime) -> None: ...


class OidcLoginAttemptsRepository(Protocol):
    async def add(self, attempt: OidcLoginAttempt) -> None: ...
    async def consume(self, state_hash: str, now: datetime) -> OidcLoginAttempt | None: ...


class UnitOfWork(Protocol):
    @property
    def users(self) -> UsersRepository: ...
    @property
    def identities(self) -> IdentitiesRepository: ...
    @property
    def profiles(self) -> ProfilesRepository: ...
    @property
    def pools(self) -> PoolsRepository: ...
    @property
    def availability(self) -> AvailabilityRepository: ...
    @property
    def constraints(self) -> ConstraintsRepository: ...
    @property
    def devices(self) -> DevicesRepository: ...
    @property
    def garmin_connections(self) -> GarminConnectionsRepository: ...
    @property
    def sync_cursors(self) -> SyncCursorsRepository: ...
    @property
    def sync_runs(self) -> SyncRunsRepository: ...
    @property
    def raw_provider_payloads(self) -> RawProviderPayloadsRepository: ...
    @property
    def activities(self) -> ActivitiesRepository: ...
    @property
    def activity_data(self) -> ActivityDataRepository: ...
    @property
    def activity_imports(self) -> ActivityImportsRepository: ...
    @property
    def goals(self) -> GoalsRepository: ...

    @property
    def goal_milestones(self) -> GoalMilestonesRepository: ...
    @property
    def workouts(self) -> WorkoutsRepository: ...
    @property
    def workout_revisions(self) -> WorkoutRevisionsRepository: ...
    @property
    def workout_schedules(self) -> WorkoutSchedulesRepository: ...
    @property
    def workout_templates(self) -> WorkoutTemplatesRepository: ...
    @property
    def action_proposals(self) -> ActionProposalsRepository: ...
    @property
    def action_approvals(self) -> ActionApprovalsRepository: ...
    @property
    def action_executions(self) -> ActionExecutionsRepository: ...
    @property
    def training_rule_sets(self) -> TrainingRuleSetsRepository: ...
    @property
    def planning_runs(self) -> PlanningRunsRepository: ...
    @property
    def training_decisions(self) -> TrainingDecisionsRepository: ...
    @property
    def external_workout_bindings(self) -> ExternalWorkoutBindingsRepository: ...
    @property
    def jobs(self) -> JobsRepository: ...
    @property
    def notifications(self) -> NotificationsRepository: ...
    @property
    def outbox(self) -> OutboxRepository: ...
    @property
    def audit(self) -> AuditRepository: ...
    @property
    def mcp_tool_invocations(self) -> McpToolInvocationsRepository: ...
    @property
    def idempotency(self) -> IdempotencyRepository: ...
    @property
    def sessions(self) -> SessionsRepository: ...
    @property
    def oidc_login_attempts(self) -> OidcLoginAttemptsRepository: ...

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...
    async def flush(self) -> None: ...
    async def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...
