"""Repository and transaction ports implemented by infrastructure adapters."""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime, timedelta
from types import TracebackType
from typing import Protocol, Self

from swim_coach.domain.athlete import (
    AthleteConstraint,
    AthleteProfile,
    AvailabilityRule,
    Device,
    Pool,
)
from swim_coach.domain.goals import GoalMilestone, TrainingGoal
from swim_coach.domain.identity import (
    AppUser,
    AuthIdentity,
    OidcLoginAttempt,
    WebSession,
)
from swim_coach.domain.operations import ApiIdempotencyRecord, AuditEvent, Job, OutboxEvent
from swim_coach.domain.shared.value_objects import EntityId, UserId


class UsersRepository(Protocol):
    async def get(self, user_id: UserId) -> AppUser | None: ...
    async def get_by_email(self, email: str) -> AppUser | None: ...
    async def add(self, user: AppUser) -> None: ...
    async def update(self, user: AppUser, *, expected_version: int) -> None: ...


class IdentitiesRepository(Protocol):
    async def get(self, provider: str, subject: str) -> AuthIdentity | None: ...
    async def add(self, identity: AuthIdentity) -> None: ...


class ProfilesRepository(Protocol):
    async def get(self, user_id: UserId) -> AthleteProfile | None: ...
    async def add(self, profile: AthleteProfile) -> None: ...
    async def update(self, profile: AthleteProfile, *, expected_version: int) -> None: ...


class PoolsRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[Pool]: ...
    async def get(self, user_id: UserId, pool_id: EntityId) -> Pool | None: ...
    async def add(self, pool: Pool) -> None: ...
    async def update(self, pool: Pool, *, expected_version: int) -> None: ...
    async def clear_default(self, user_id: UserId, *, except_id: EntityId) -> None: ...


class AvailabilityRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[AvailabilityRule]: ...
    async def replace(self, user_id: UserId, rules: Sequence[AvailabilityRule]) -> None: ...


class ConstraintsRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[AthleteConstraint]: ...
    async def add(self, constraint: AthleteConstraint) -> None: ...


class DevicesRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[Device]: ...
    async def add(self, device: Device) -> None: ...


class GoalsRepository(Protocol):
    async def list(self, user_id: UserId) -> Sequence[TrainingGoal]: ...
    async def get(self, user_id: UserId, goal_id: EntityId) -> TrainingGoal | None: ...
    async def add(self, goal: TrainingGoal) -> None: ...
    async def update(self, goal: TrainingGoal, *, expected_version: int) -> None: ...


class GoalMilestonesRepository(Protocol):
    async def list(self, user_id: UserId, goal_id: EntityId) -> Sequence[GoalMilestone]: ...
    async def add(self, milestone: GoalMilestone) -> None: ...


class JobsRepository(Protocol):
    async def add(self, job: Job) -> None: ...
    async def lease_next(
        self, worker_id: str, *, ttl: timedelta, job_types: frozenset[str]
    ) -> Job | None: ...
    async def mark_succeeded(self, job_id: EntityId, worker_id: str, at: datetime) -> bool: ...


class OutboxRepository(Protocol):
    async def add(self, event: OutboxEvent) -> None: ...


class AuditRepository(Protocol):
    async def add(self, event: AuditEvent) -> None: ...


class IdempotencyRepository(Protocol):
    async def get(self, scope: str, key: str, now: datetime) -> ApiIdempotencyRecord | None: ...
    async def add(self, record: ApiIdempotencyRecord) -> None: ...


class SessionsRepository(Protocol):
    async def add(self, session: WebSession) -> None: ...
    async def get_active_by_token_hash(
        self, token_hash: str, now: datetime
    ) -> WebSession | None: ...
    async def revoke(self, session_id: EntityId, at: datetime) -> None: ...


class OidcLoginAttemptsRepository(Protocol):
    async def add(self, attempt: OidcLoginAttempt) -> None: ...
    async def consume(self, state_hash: str, now: datetime) -> OidcLoginAttempt | None: ...


class UnitOfWork(Protocol):
    @property
    def users(self) -> UsersRepository: ...
    @property
    def identities(self) -> IdentitiesRepository: ...
    @property
    def profiles(self) -> ProfilesRepository: ...
    @property
    def pools(self) -> PoolsRepository: ...
    @property
    def availability(self) -> AvailabilityRepository: ...
    @property
    def constraints(self) -> ConstraintsRepository: ...
    @property
    def devices(self) -> DevicesRepository: ...
    @property
    def goals(self) -> GoalsRepository: ...

    @property
    def goal_milestones(self) -> GoalMilestonesRepository: ...
    @property
    def jobs(self) -> JobsRepository: ...
    @property
    def outbox(self) -> OutboxRepository: ...
    @property
    def audit(self) -> AuditRepository: ...
    @property
    def idempotency(self) -> IdempotencyRepository: ...
    @property
    def sessions(self) -> SessionsRepository: ...
    @property
    def oidc_login_attempts(self) -> OidcLoginAttemptsRepository: ...

    async def __aenter__(self) -> Self: ...

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...
    async def flush(self) -> None: ...
    async def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...
