"""p01 foundation

Revision ID: 000001
Revises:
Create Date: 2026-08-11 19:45:00.180001
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "000001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_idempotency_record",
        sa.Column("scope", sa.String(length=160), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("request_hash", sa.String(length=128), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("expires_at > created_at", name="ck_idempotency_expiry"),
        sa.PrimaryKeyConstraint("scope", "idempotency_key"),
    )
    op.create_index("ix_idempotency_expiry", "api_idempotency_record", ["expires_at"], unique=False)
    op.create_table(
        "app_user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("locale", sa.String(length=35), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("status IN ('active','disabled','deleted')", name="ck_app_user_status"),
        sa.CheckConstraint("version >= 1", name="ck_app_user_version"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_app_user_email_ci", "app_user", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "oidc_login_attempt",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("code_verifier", sa.String(length=160), nullable=False),
        sa.Column("nonce", sa.String(length=160), nullable=False),
        sa.Column("redirect_uri", sa.String(length=2048), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("state_hash"),
    )
    op.create_index(
        "ix_oidc_login_attempt_active",
        "oidc_login_attempt",
        ["state_hash", "expires_at"],
        unique=False,
        postgresql_where=sa.text("consumed_at IS NULL"),
    )
    op.create_table(
        "athlete_constraint",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=False),
        sa.Column("active_from", sa.Date(), nullable=False),
        sa.Column("active_until", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "active_until IS NULL OR active_from <= active_until",
            name="ck_athlete_constraint_dates",
        ),
        sa.CheckConstraint("severity BETWEEN 1 AND 5", name="ck_athlete_constraint_severity"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_athlete_constraint_user_active",
        "athlete_constraint",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_type", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=False),
        sa.Column("action", sa.String(length=160), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("before_json_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_json_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("ip_hash", sa.String(length=128), nullable=True),
        sa.Column("user_agent_summary", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_event_correlation", "audit_event", ["correlation_id"], unique=False)
    op.create_index(
        "ix_audit_event_user_created",
        "audit_event",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "auth_identity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("claims_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "subject", name="uq_auth_identity_provider_subject"),
    )
    op.create_index("ix_auth_identity_user", "auth_identity", ["user_id"], unique=False)
    op.create_table(
        "device",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("external_device_id", sa.String(length=255), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("serial_hash", sa.String(length=128), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("capabilities_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_device_id", name="uq_device_provider_external"),
    )
    op.create_index("ix_device_user", "device", ["user_id"], unique=False)
    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column("locked_by", sa.String(length=120), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_error_json_redacted", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('QUEUED','LEASED','RUNNING','SUCCEEDED','RETRY_SCHEDULED',"
            "'FAILED_TERMINAL','NEEDS_RECONCILIATION')",
            name="ck_job_status",
        ),
        sa.CheckConstraint("attempts >= 0 AND max_attempts >= 1", name="ck_job_attempts"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_job_available",
        "job",
        ["status", "available_at", sa.literal_column("priority DESC")],
        unique=False,
        postgresql_where=sa.text("status IN ('QUEUED','RETRY_SCHEDULED')"),
    )
    op.create_table(
        "outbox_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=160), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("causation_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_outbox_unpublished",
        "outbox_event",
        ["occurred_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_table(
        "pool",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("length_m", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("location_label", sa.String(length=160), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("length_m > 0", name="ck_pool_length_positive"),
        sa.CheckConstraint("version >= 1", name="ck_pool_version"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pool_user", "pool", ["user_id"], unique=False)
    op.create_index(
        "uq_pool_one_default_per_user",
        "pool",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "training_goal",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("target_distance_m", sa.Integer(), nullable=False),
        sa.Column("target_duration_seconds", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column(
            "target_pace_seconds_per_100m", sa.Numeric(precision=12, scale=3), nullable=False
        ),
        sa.Column("baseline_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft','active','completed','cancelled')", name="ck_goal_status"
        ),
        sa.CheckConstraint("target_distance_m > 0", name="ck_training_goal_distance"),
        sa.CheckConstraint("target_duration_seconds > 0", name="ck_training_goal_duration"),
        sa.CheckConstraint("target_pace_seconds_per_100m > 0", name="ck_training_goal_pace"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_training_goal_user_status", "training_goal", ["user_id", "status"], unique=False
    )
    op.create_table(
        "web_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "ix_web_session_active",
        "web_session",
        ["token_hash", "expires_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "athlete_profile",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("experience_level", sa.String(length=40), nullable=False),
        sa.Column("preferred_distance_unit", sa.String(length=10), nullable=False),
        sa.Column("default_pool_id", sa.Uuid(), nullable=True),
        sa.Column("default_sessions_per_week", sa.Integer(), nullable=False),
        sa.Column("goal_notes", sa.Text(), nullable=True),
        sa.Column(
            "coach_preferences_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("preferred_distance_unit = 'm'", name="ck_athlete_profile_unit"),
        sa.CheckConstraint(
            "default_sessions_per_week BETWEEN 1 AND 14", name="ck_athlete_profile_sessions"
        ),
        sa.CheckConstraint("version >= 1", name="ck_athlete_profile_version"),
        sa.ForeignKeyConstraint(["default_pool_id"], ["pool.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "availability_rule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_local_time", sa.Time(), nullable=False),
        sa.Column("end_local_time", sa.Time(), nullable=False),
        sa.Column("max_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("pool_id", sa.Uuid(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("day_of_week BETWEEN 0 AND 6", name="ck_availability_weekday"),
        sa.CheckConstraint("max_duration_minutes > 0", name="ck_availability_duration"),
        sa.CheckConstraint("start_local_time < end_local_time", name="ck_availability_time"),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_from IS NULL OR valid_from <= valid_until",
            name="ck_availability_validity",
        ),
        sa.ForeignKeyConstraint(["pool_id"], ["pool.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_availability_user_day", "availability_rule", ["user_id", "day_of_week"], unique=False
    )
    op.create_table(
        "goal_milestone",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("target_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["training_goal.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_goal_milestone_goal", "goal_milestone", ["goal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_goal_milestone_goal", table_name="goal_milestone")
    op.drop_table("goal_milestone")
    op.drop_index("ix_availability_user_day", table_name="availability_rule")
    op.drop_table("availability_rule")
    op.drop_table("athlete_profile")
    op.drop_index(
        "ix_web_session_active",
        table_name="web_session",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("web_session")
    op.drop_index("ix_training_goal_user_status", table_name="training_goal")
    op.drop_table("training_goal")
    op.drop_index(
        "uq_pool_one_default_per_user", table_name="pool", postgresql_where=sa.text("is_default")
    )
    op.drop_index("ix_pool_user", table_name="pool")
    op.drop_table("pool")
    op.drop_index(
        "ix_outbox_unpublished",
        table_name="outbox_event",
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.drop_table("outbox_event")
    op.drop_index(
        "ix_job_available",
        table_name="job",
        postgresql_where=sa.text("status IN ('QUEUED','RETRY_SCHEDULED')"),
    )
    op.drop_table("job")
    op.drop_index("ix_device_user", table_name="device")
    op.drop_table("device")
    op.drop_index("ix_auth_identity_user", table_name="auth_identity")
    op.drop_table("auth_identity")
    op.drop_index("ix_audit_event_user_created", table_name="audit_event")
    op.drop_index("ix_audit_event_correlation", table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index("ix_athlete_constraint_user_active", table_name="athlete_constraint")
    op.drop_table("athlete_constraint")
    op.drop_index(
        "ix_oidc_login_attempt_active",
        table_name="oidc_login_attempt",
        postgresql_where=sa.text("consumed_at IS NULL"),
    )
    op.drop_table("oidc_login_attempt")
    op.drop_index("uq_app_user_email_ci", table_name="app_user")
    op.drop_table("app_user")
    op.drop_index("ix_idempotency_expiry", table_name="api_idempotency_record")
    op.drop_table("api_idempotency_record")
    # ### end Alembic commands ###
